# AdPlug Makefile for Watcom and OpenWatcom
# Copyright (c) 2002, 2003 Simon Peter <dn.tlp@gmx.net>

SUBDIRS = src adplugdb

AUX = README AUTHORS NEWS COPYING TODO BUGS ChangeLog INSTALL README.dos
DIST = src\*.c src\*.cpp src\*.h src\Makefile.bt adplugdb\*.cpp adplugdb\*.c &
adplugdb\*.h adplugdb\Makefile.bt $(AUX)
BINARYDIST = src\*.h src\adplug.lib adplugdb\adplugdb.exe $(AUX)

distfile = adpl141s.zip
binarydistfile = adplg141.zip
installfile = INSTALL.dos
