# AdPlug Makefile for Watcom and OpenWatcom
# Copyright (c) 2002, 2003 Simon Peter <dn.tlp@gmx.net>

SUBDIRS = src adplugdb

AUX = doc\*.ms README AUTHORS NEWS COPYING TODO ChangeLog
DIST = src\*.c src\*.cpp src\*.h src\Makefile.bt $(AUX) INSTALL
BINARYDIST = src\*.h src\adplug.lib $(AUX)

distfile = adplg14s.zip
binarydistfile = adplug14.zip
installfile = INSTALL.dos
