# AdPlug Makefile for Watcom and OpenWatcom
# Copyright (c) 2003 Simon Peter <dn.tlp@gmx.net>

CPPFLAGS = -dHAVE_STRING_H

OUTPUT = adplugdb.exe

LIBRARIES = ..\src\adplug.lib binio.lib
OBJS = adplugdb.obj getopt.obj

bin_INST = adplugdb.exe
