#!/bin/sh

# Produce ps output
groff -t -m ms -T ps Hacking.ms > Hacking.ps
groff -t -m ms -T ps Player-Development.ms > Player-Development.ps
groff -t -m ms -T ps Protracker.ms > Protracker.ps

# Produce ASCII output
groff -t -m ms -T ascii Hacking.ms > Hacking.txt
groff -t -m ms -T ascii Player-Development.ms > Player-Development.txt
groff -t -m ms -T ascii Protracker.ms > Protracker.txt
